name: Just_tabata_timer
description: interval timer for hmb

# Prevent accidentally publishing to pub.dev using `pub publish`
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.16.0
  flutter_colorpicker: ^0.3.4
  numberpicker: ^1.3.0
  screen: ^0.0.5
  shared_preferences: ^0.5.12+4
  flutter_speech : "^1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/boop.mp3
  - assets/dingdingding.mp3
  - assets/pip.mp3
